### ISSUE TITLE
Brew formula is outdated

### ISSUE THREAD

**Issue by cristaloleg** [moderato-app/approf#18] opened 2024-09-03 09:58 UTC
Hey, I have a problem installing `approf`:

```
% brew install approf

appr    Warning: No available formula with the name "approf". Did you mean apprise?
==> Searching for similarly named formulae and casks...
==> Formulae
apprise

To install apprise, run:
  brew install apprise
```

Looks like steps from README are not valid anymore.

Thanks for the tool btw.

**Comment by clement2026** [comment] 2024-09-03 15:36
@cristaloleg Thanks for you interest in this project!

https://formulae.brew.sh/cask/approf#default

I just tried installing `approf` using `brew install approf`, and it worked fine on my macbook.

Since `approf` needs macOS 14.0 or later, could you check your OS version?

**Comment by cristaloleg** [comment] 2024-09-03 17:24
I'm on macOS 14.5. The problem with README is that it suggests `brew install approf` without `--cask`.

Anyway, with `--cask` it doesn't work either:

```
% brew install --cask approf
Warning: Cask 'approf' is unavailable: No Cask with this name exists.
==> Searching for similarly named casks...
Error: No casks found for approf.
```

🤷

**Comment by clement2026** [comment] 2024-09-04 01:18
That's odd🤔. I need some time to figure out what's happening.

In the meantime, you can download the app from: https://github.com/moderato-app/approf/releases/tag/v14.1.3

**Comment by clement2026** [comment] 2024-09-04 01:32
Could you check the git revision of your brew repo with this command?

```bash
git -C $(brew --repo homebrew/cask) log -n 5
```

<img width="745" alt="image" src="https://github.com/user-attachments/assets/72446043-6368-4087-97ac-ad305bb5fcb7">


---
<img width="745" alt="image" src="https://github.com/user-attachments/assets/cd658938-1499-4cc7-9088-5566d9d1d833">

**Comment by cristaloleg** [comment] 2024-09-04 13:46
```
homebrew-cask-versions % git log -n 5
commit 057d1202c4ac9d4059909260af8d13e20fbf8cab (HEAD -> master, origin/master, origin/HEAD)
Merge: 082412cf30 b2602d2509
Author: Miccal Matthews <miccal.matthews@gmail.com>
Date:   Fri May 3 04:42:57 2024 +0800

    Merge pull request #20219 from Homebrew/deprecate
    
    Deprecate repository

commit b2602d2509f8839e8fd11618091d4e082627e161
Author: Patrick Linnane <patrick@linnane.io>
Date:   Thu May 2 11:09:16 2024 -0700

    Deprecate repository
    
    Signed-off-by: Patrick Linnane <patrick@linnane.io>

commit 082412cf30083b63e7734e8c676a7827b0082c25
Merge: 877bb10b71 8d33e587a9
Author: Razvan Azamfirei <azamfireirazvan@gmail.com>
Date:   Thu May 2 20:41:26 2024 +0300

    Merge pull request #20218 from Homebrew/migrate-semeru-jdk

commit 877bb10b7164df1ea309cd7038f862ab9f72e102
Merge: 5880bf59a6 1c1c153bc7
Author: Patrick Linnane <patrick@linnane.io>
Date:   Thu May 2 10:37:23 2024 -0700

    Merge pull request #20213 from Homebrew/deprecate-daedalus

commit 5880bf59a626b3592602f26cabbc2ea844015587
Merge: 2885a3bd13 4b7a83a737
Author: Patrick Linnane <patrick@linnane.io>
Date:   Thu May 2 10:28:30 2024 -0700

    Merge pull request #20217 from Homebrew/migrate-parallels15
```

**Comment by clement2026** [comment] 2024-09-06 00:32
A friend of mine confirmed that `brew install approf` works on their MacBook.

Looks like your brew hasn't been updated for 4 months. That might be causing some issues. Can you give `brew update` a shot and then run `brew install approf`?


* [How to stop Homebrew auto update on mac terminal](https://dev.to/ankitmalikg/how-to-stop-homebrew-auto-update-on-mac-terminal-hb0)

**Comment by clement2026** [comment] 2024-09-10 04:55
@cristaloleg did you manage to run `brew install approf`?  I’m still curious about what caused the issue.

**Comment by clement2026** [comment] 2024-09-21 08:30
no updates, closing this

**Closed as completed by clement2026** 2024-09-21 08:30 UTC

**Comment by cristaloleg** [comment] 2024-09-21 13:16
Yes, everything is fixed. Forgot to answer earlier, thanks!
